### ISSUE TITLE
Viridia Icon/Logo

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#13]
### Situation: What is the current situation you want to enhance?

We don't have an icon/logo yet.

### Task: What is the general task?

Help build identity with a logo

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create a few logo designs (ChatGPT, Midjourney, StableDiffusion, or another way)
- [ ] Present the designs to the team to vote for the best
- [ ] Optional: Contact Lisa about the logo
- [ ] Check for license (?)
- [ ] Use the logo when possible

### Result: What is the desired output/goal, you want to reach?

Increased Project and Product Identity with a logo.
Made sure we are allowed to use the logo and have all needed licenses.

**Comment by mroxso** [comment]
We voted internally for a Logo. It has to be graphically refined now.

**Comment by mroxso** [comment]
I contacted Lisa about that
