### ISSUE TITLE
Introduce Github Terraform Provider

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#14]
### Situation: What is the current situation you want to enhance?

We need to manually set up repository level permissions.

### Task: What is the general task?

Introduce Github Terraform provider.

### Action: List step-by-step todos or actions on how to do the task

- [ ] Define Permissions per Scope to set (Permission-Matrix)
- [ ] Who needs which permissions 
- [ ] Create Repository for terraform code
- [ ] Create UI to set permissions on merge ("Workflow dispatch")
- [ ] Create CI/CD Pipeline/Workflow

### Result: What is the desired output/goal, you want to reach?

Introduced a streamlined process to set up permissions via Github Terraform provider
