### ISSUE TITLE
Define Folder Structure for Repositories

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#18]
### Situation: What is the current situation you want to enhance?

We don't have a defined folder structure for the repositories. This makes it hard to define code owners.

### Task: What is the general task?

Research folder structure best-practices and define a structure for our main repositories. 

### Action: List step-by-step todos or actions on how to do the task

- [ ] Research Best-Practices
- [ ] Define Structure for main repo (Go Code)
- [ ] Define Structure for Docu Repository
- [ ] Define Structure for Infrastructure Repository
- [ ] Brainstorm other possible repositories we might need
- [ ] Layout a folder structure for them aswell

### Result: What is the desired output/goal, you want to reach?

Defined folder structure and enable code owner definition

**Comment by sebastian-grabsch-pexon** [comment]
- .github/ISSUE_TEMPLATE/
- viridia/
    - backend
        - package1/
        - package2/
        - ...
    - frontend
    - resources
    - ...
    - go.mod
    - main.go
- LICENSE
- README.md

**Comment by JaegerP** [comment]
@sebastian-grabsch-pexon Wollten wir nicht mit Go arbeiten? Python ist für mich auch fein, wir sollen es nur mal klären, bevor wir loslegen.

**Comment by sebastian-grabsch-pexon** [comment]
Achso ja doch klar, wir arbeiten mit Go.

**Comment by JaegerP** [comment]
Auch bei den Ordnern möchte ich gerne meckern. Wir brauchen ja einen Controller, einen Host Agent, und wahrscheinlich einen Config Manager. Das sollten unterschiedliche Repos werden am besten.

Die Go Testing Library gibt auch vor, dass die test files mit in den Modulen liegen - also brauchen wir keinen eigenen Ordner für Tests

**Comment by sebastian-grabsch-pexon** [comment]
"The test file can be in the same package as the one being tested, or in a corresponding package with the suffix "_test"."
Soweit ich das verstehe kann der auch separat liegen. Ich finds in der Regel sehr angenehm, die Tests abgegrenzt zu haben. Ich freue mich aber auch über Input bzgl Best Practices, da ich ja auch Go Newbie bin
