### ISSUE TITLE
Viridia Architecture Epic

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#21]
Management Epic for Architecture Epics

- [ ] Extern Technical Solution (e.g. Carbon Intensity API, ...)
- [ ] Intern Technical Solution (e.g. Raft Leader Election, Hosts, Scheduling, etc.)
- [ ] How-To/Quickstart-Guide
