### ISSUE TITLE
Intern: Boilerplate Code / Setup Project Structure

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#25]
### Situation: What is the current situation you want to enhance?

We want to avoid unclear project structure.

### Task: What is the general task?

Create scaffolding for Viridia Repo

### Action: List step-by-step todos or actions on how to do the task

- [ ] Setup Go Project
- [ ] Initialize Go Module
- [ ] Setup Project Structure
- [ ] Create Boilerplate-Files
- [ ] Create Project entry
- [ ] Create test-files

### Result: What is the desired output/goal, you want to reach?

Have a clear structure everyone can follow
