### ISSUE TITLE
Intern: Nodes

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#27]
### Situation: What is the current situation you want to enhance?

We need a node construct as a fundamental building block

### Task: What is the general task?

Create Nodes 

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create Node struct #38 
- [ ] Setup Boilerplate for raft
- [ ] Implement Raft specification
- [ ] Implement Node Boilerplate using raft
- [ ] Implement Boilerplate methods
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Baseline structure for nodes created
