### ISSUE TITLE
Intern: Leader Election

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#28]
### Situation: What is the current situation you want to enhance?

We need a baseline understanding of the election process via a Proposer

### Task: What is the general task?

Model a proposal logic

### Action: List step-by-step todos or actions on how to do the task

- [ ] Proposal Package
- [ ] Define Handler interface
- [ ] Create Handler Registry
- [ ] Create Code for Handler/Runners
- [ ] Create Proposal structure
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Usable proposer for leader election
