### ISSUE TITLE
Intern: Storage

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#29]
### Situation: What is the current situation you want to enhance?

We want to store data of different types

### Task: What is the general task?

Create storage structure for etcd

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create storage interface
- [ ] Create etcd storage struct
- [ ] Initialize etcd client
- [ ] Implement etcd driver
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Have a usable etcd implementation for storage
