### ISSUE TITLE
Intern: Container

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#30]
### Situation: What is the current situation you want to enhance?

We need a ground structure to run workloads

### Task: What is the general task?

Create Containers to run Workloads (Docker-Images) programatically

### Action: List step-by-step todos or actions on how to do the task

- [ ] Initialize Docker client
- [ ] Create Docker client struct
- [ ] Implement needed methods 
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Runnable Docker images inside the container
