### ISSUE TITLE
Intern: Task-Management

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#31]
### Situation: What is the current situation you want to enhance?

We need a way to manage tasks

### Task: What is the general task?

Design and implement a task/command structure and a way to manage them

### Action: List step-by-step todos or actions on how to do the task

- [ ] Model Task interface
- [ ] Model Task definition
- [ ] Implement Tasks
- [ ] Implement Task Definition
- [ ] Create Task Manager
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Clean Task Management for the whole system
