### ISSUE TITLE
Intern: CLI

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#32]
### Situation: What is the current situation you want to enhance?

A CLI is a simple entry point wrapper

### Task: What is the general task?

We want a CLI to enable flexible steering of the System

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create Flag Parser
- [ ] Reference Main Entry Points
- [ ] Create CLI Flags for each module
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Have a usable CLI to enter the cluster
