### ISSUE TITLE
Extern: Aggregation Framework

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#33]
### Situation: What is the current situation you want to enhance?

We need external information to enrich our system

### Task: What is the general task?

Build an aggregation Framework to gather data from various data points

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create External Repository
- [ ] Create aggregation project
- [ ] Setup Data Receivers
- [ ] Create Data Modelling
- [ ] Create Aggregation Algorithm
- [ ] Expose Data in some way (internal API, ...)
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

have a single point of entry for data to calucate PUs for nodes
