### ISSUE TITLE
External: Pricing Hysteresis

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#34]
### Situation: What is the current situation you want to enhance?

If we always schedule on the current cheapest region/node, we might run into the situation of switching workloads too often, when e.g. the price for energy fluctuates heavily

### Task: What is the general task?

Create a hysteresis logic to smoothen pricing

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create Hysteresis Repository
- [ ] Create Hysteresis logic 
- [ ] Implement Hysteresis logic
- [ ] Create API Endpoints
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Get a smooth indicator of efficient resource usage
