### ISSUE TITLE
External: API

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#35]
### Situation: What is the current situation you want to enhance?

We might run into the situation of unclear defined apis

### Task: What is the general task?

Define API Layouts for the whole ecosystem

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create API Repository
- [ ] Define APIs for each communication interface
- [ ] Implement API reference endpoints
- [ ] Create tests

### Result: What is the desired output/goal, you want to reach?

Single point of API definitions throughout the whole ecosystem
