### ISSUE TITLE
FAQ Einstieg

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#36]
### Situation: What is the current situation you want to enhance?

Currently we start explaining the whys and hows to each project new joiner.

### Task: What is the general task?

Create a FAQ Thread in the documentation repository to answer the most common initial questions.

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create FAQ Entry
- [ ] Answer the following questions
    - 1. Why did we start the project / Whats the use case for the product?
    - 2. Roles / Contacts
    - 3. Accountabilities for specific epics
    - 4. Maybe: Teammembers 
    - 5. Story Point Mappings

- [ ] Add other relevant questions

### Result: What is the desired output/goal, you want to reach?

Avoid answering the same questions over and over. Have a reference to point new member to
