### ISSUE TITLE
Nodes: Create Node Struct

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#38]
### Situation: What is the current situation you want to enhance?

We need a baseline node struct.

### Task: What is the general task?

We want to implement the Node and run init it in main

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create Node Struct Boilerplate
- [ ] Init of Node Struct in main.go
- [ ] Create Node _test.go to test basic functionality
- [ ] Create documentation

### Result: What is the desired output/goal, you want to reach?

Baseline Node Struct
