### ISSUE TITLE
Nodes: Make port to join customizable

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#39]
### Situation: What is the current situation you want to enhance?

For the MVP we use a hard coded IP to start/join.

### Task: What is the general task?

We want the IP to be customizable to enable multi-cluster on one machine

### Action: List step-by-step todos or actions on how to do the task

- [ ] Create/Extend the CLI with a "-join [PORT]"
- [ ] Test multi-cluster setup locally
- [ ] Extend Quick-Start
- [ ] Extend Documentation

### Result: What is the desired output/goal, you want to reach?

Have a flexible port/ip on cluster creation
