### ISSUE TITLE
TBR: Nodes: Load carbon-intensity data for node from External

### ISSUE THREAD

**Issue by RELAXccc** [Viridia-Pexon/viridia#40]
### Situation: What is the current situation you want to enhance?

Implement

### Task: What is the general task?

The Node has to repeatedly load and store the carbon-intesity value from the external PU API.

### Action: List step-by-step todos or actions on how to do the task

- [ ] define rules for refreshing carbon-intesity
- [ ] implement API call using fasthttp and store value in local struct
- [ ] discuss way of storage (remember old values y/n?) 
- [ ] discuss what happens if PU API is not reachable

### Result: What is the desired output/goal, you want to reach?

Every node is aware of its carbon-intensity value at any point in time
